### ISSUE TITLE
It doesnt count invites

### ISSUE THREAD

**Issue by chitrakshbotwala** [serendiasquad/invite-manager#10]
I invited told one of my friends who was already in the server to leave and rejoin but when he joined it didnt count the invites or add one to me

**Comment by aloshai** [comment]
Sometimes there are times when the bot cannot count or find invitations meaninglessly. When you invite someone, you need to make sure that the invite link you send to that person is yours. **Also, make sure all settings on the bot are set.**

**Comment by chitrakshbotwala** [comment]
ohk Thanks for the reply :)

**Comment by aloshai** [comment]
you're welcome
