### ISSUE TITLE
[Suggestion status]

### ISSUE THREAD

**Issue by cTmoNe** [serendiasquad/invite-manager#12]
Hello, can you add a status for bot, Playing/Watching/Listening?

**Comment by aloshai** [comment]
Can you do yourself.
You should be look [setPresence](https://discord.js.org/#/docs/main/stable/class/ClientUser?scrollTo=setPresence) method

Create a new Ready Event Listener. For example:
```javascript
client.on("ready", () => {
    // Your codes...
});
```
and write to client presence change method but you should look [PresenceData](https://discord.js.org/#/docs/main/stable/typedef/PresenceData) class
```javascript
client.user.setPresence({
    activity: {
        name: "I am now playing...",
        type: "PLAYING"
    }
});
```

and result: 
```javascript
client.on("ready", () => {
    client.user.setPresence({
        activity: {
            name: "I am now playing...",
            type: "PLAYING"
        }
    });
});
```
