### ISSUE TITLE
Yeni sürümde eklenebilecekler.

### ISSUE THREAD

**Issue by xatiapriw** [serendiasquad/invite-manager#4]
- Dil sistemi (TR-EN)
- Gelişmiş ayarlanabilir, Giriş-Çıkış Mesajları 
- Ayarlanabilir Prefix

**Comment by aloshai** [comment]
Dil sistemi gibi bir düşüncem var. Giriş-Çıkış mesajları zaten ayarlanabiliyor `!options welcomeMessage <content>` tarzı bir komut kullanarak bunu yapabilirsin. Prefix işini bilmiyorum, eğer kafama eserse yaparım.
