### ISSUE TITLE
daveti olmıyan biri davetine bakınca bot kapanıyor

### ISSUE THREAD

**Issue by mhmtx4** [serendiasquad/invite-manager#5]
**daveti olmıyan biri davetine bakınca bot kapanıyor**
**vede giriş çıkış mesajları yeni olarak gelebilir**

**Comment by aloshai** [comment]
Birazcık göz gezdirdim ancak bunun mümkün olmadığını söylemek isterim. En azından benim gördüğüm kadarıyla. Yaşadığın sorun her ne ise bana bunu adım adım anlat ya da ekran görüntüsü olarak atar mısın?
