### ISSUE TITLE
help

### ISSUE THREAD

**Issue by shadowTW** [serendiasquad/invite-manager#9]
how can I make [prefix]config joinChannel #channel like without the channel id

**Comment by Lebyy** [comment]
Use channel mention

**Comment by shadowTW** [comment]
not working

**Comment by aloshai** [comment]
Currently it is not possible to specify joinChannel in that command without using the channel id.

**Comment by Lebyy** [comment]
I did it without using Id.

**Comment by Lebyy** [comment]
I'll post it here in a sec.
